"""esquema inicial

Revision ID: c2f06bd69eea
Revises: 
Create Date: 2026-09-22 23:21:02.549619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f06bd69eea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('criterios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterios_organization_id'), 'criterios', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('prefijo', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_uso_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('revertido', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_creado_en'), 'audit_log', ['creado_en'], unique=False)
    op.create_index(op.f('ix_audit_log_entidad_id'), 'audit_log', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_table('filtros_guardados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtros_guardados_user_id'), 'filtros_guardados', ['user_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('entidad_ref', sa.String(length=100), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('enviado_email', sa.Boolean(), nullable=False),
    sa.Column('enviado_slack', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_creado_en'), 'notificaciones', ['creado_en'], unique=False)
    op.create_index(op.f('ix_notificaciones_user_id'), 'notificaciones', ['user_id'], unique=False)
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('fuentes_informacion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectores_organization_id'), 'sectores', ['organization_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('menciones_user_ids', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_sector_id'), 'comentarios', ['sector_id'], unique=False)
    op.create_table('rondas_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rondas_evaluacion_sector_id'), 'rondas_evaluacion', ['sector_id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='ck_calificacion_1_a_5'),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ronda_id'], ['rondas_evaluacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ronda_id', 'criterio_id', name='uq_evaluacion_ronda_criterio')
    )
    op.create_index(op.f('ix_evaluaciones_criterio_id'), 'evaluaciones', ['criterio_id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_ronda_id'), 'evaluaciones', ['ronda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluaciones_ronda_id'), table_name='evaluaciones')
    op.drop_index(op.f('ix_evaluaciones_criterio_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_rondas_evaluacion_sector_id'), table_name='rondas_evaluacion')
    op.drop_table('rondas_evaluacion')
    op.drop_index(op.f('ix_comentarios_sector_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_sectores_organization_id'), table_name='sectores')
    op.drop_table('sectores')
    op.drop_index(op.f('ix_notificaciones_user_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_creado_en'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_filtros_guardados_user_id'), table_name='filtros_guardados')
    op.drop_table('filtros_guardados')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidad_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_creado_en'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_criterios_organization_id'), table_name='criterios')
    op.drop_table('criterios')
    op.drop_table('organizations')
    # ### end Alembic commands ###
