"""invitaciones, slack por organizacion

Revision ID: f59260119d04
Revises: c2f06bd69eea
Create Date: 2026-09-23 00:49:17.284945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59260119d04'
down_revision: Union[str, Sequence[str], None] = 'c2f06bd69eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tablas/columnas DateTime que antes se declaraban sin timezone=True. En
# SQLite esto no cambia nada en el DDL (no tiene un tipo tz-aware nativo),
# pero en Postgres sí es una diferencia real: TIMESTAMP WITHOUT TIME ZONE
# vs TIMESTAMP WITH TIME ZONE. Sin esto, Postgres guardaba las fechas
# "ingenuas" (perdía la zona horaria de datetime.now(timezone.utc)) y el
# orden por fecha podía quedar mal si el server no corría en UTC.
_COLUMNAS_A_TZ_AWARE = [
    ("organizations", "creado_en"),
    ("users", "creado_en"),
    ("sectores", "fecha_creacion"),
    ("rondas_evaluacion", "creado_en"),
    ("audit_log", "creado_en"),
    ("comentarios", "creado_en"),
    ("notificaciones", "creado_en"),
    ("api_keys", "creado_en"),
    ("api_keys", "ultimo_uso_en"),
    ("filtros_guardados", "creado_en"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('usada', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitaciones_email'), 'invitaciones', ['email'], unique=False)
    op.create_index(op.f('ix_invitaciones_organization_id'), 'invitaciones', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitaciones_token'), 'invitaciones', ['token'], unique=True)
    op.add_column('organizations', sa.Column('slack_webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    # batch_alter_table: en SQLite recrea la tabla (es la única forma de
    # "alterar" una columna ahí); en Postgres hace el ALTER COLUMN directo.
    for tabla, columna in _COLUMNAS_A_TZ_AWARE:
        with op.batch_alter_table(tabla) as batch_op:
            batch_op.alter_column(columna, type_=sa.DateTime(timezone=True))


def downgrade() -> None:
    """Downgrade schema."""
    for tabla, columna in _COLUMNAS_A_TZ_AWARE:
        with op.batch_alter_table(tabla) as batch_op:
            batch_op.alter_column(columna, type_=sa.DateTime(timezone=False))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'slack_webhook_url')
    op.drop_index(op.f('ix_invitaciones_token'), table_name='invitaciones')
    op.drop_index(op.f('ix_invitaciones_organization_id'), table_name='invitaciones')
    op.drop_index(op.f('ix_invitaciones_email'), table_name='invitaciones')
    op.drop_table('invitaciones')
    # ### end Alembic commands ###
